<?php

namespace AppBundle\Repository;
use Symfony\Component\Validator\Constraints\Count;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function get5Comentators()
    {
        //SELECT `user_id`, COUNT(user_id) as qty_comment FROM `comments` GROUP BY `user_id` ORDER BY qty_comment DESC
        return $this
            ->createQueryBuilder('c')
            ->select('count(c.user)')
            ->select('IDENTITY(c.user) AS user_id')
            ->groupBy('user_id')
            ->getQuery()
            ->getResult()
            ;
    }

    public function get3TopNews()
    {
        return $this
            ->createQueryBuilder('c')
            ->select('count(c.post)')
            ->select('IDENTITY(c.post) AS post_id')
            ->groupBy('post_id')
            ->getQuery()
            ->getResult()
            ;
    }
}
