<?php

namespace AppBundle\Repository;

/**
 * ModerateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModerateRepository extends \Doctrine\ORM\EntityRepository
{
}
