<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function get4indexNews()
    {
        return $this
            ->createQueryBuilder('post')
            ->orderBy('post.id','DESC')
            ->setMaxResults(4)
            ->getQuery()
            ->getResult()
            ;
    }

    public function get5Analitic()
    {
        return $this
            ->createQueryBuilder('post')
            ->where('post.tags = 3')
            ->orderBy('post.id','DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult()
            ;
    }

    public function get5Economy()
    {
        return $this
            ->createQueryBuilder('post')
            ->where('post.category = 4')
            ->having('post.tags != 3')
            ->orderBy('post.id','DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult()
        ;
    }

//SELECT * FROM `post` WHERE category_id=4 AND tags_id != 3 ORDER BY id DESC LIMIT 5

    public function get5Policy()
    {
        return $this
            ->createQueryBuilder('post')
            ->where('post.category = 1')
            ->having('post.tags != 3')
            ->orderBy('post.id','DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult()
        ;
    }

    public function get5FinForec()
    {
        return $this
            ->createQueryBuilder('post')
            ->where('post.category = 3')
            ->having('post.tags != 3')
            ->orderBy('post.id','DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult()
        ;
    }

    public function get5FinNews()
    {
        return $this
            ->createQueryBuilder('post')
            ->where('post.category = 2')
            ->having('post.tags != 3')
            ->orderBy('post.id','DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult()
        ;
    }

    public function getEconomy()
    {
        return $this
            ->createQueryBuilder('post')
            ->where('post.category = 4')
            ->having('post.tags != 3')
            ->orderBy('post.id','DESC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function getPolicy()
    {
        return $this
            ->createQueryBuilder('post')
            ->where('post.category = 1')
            ->having('post.tags != 3')
            ->orderBy('post.id','DESC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function getFinForec()
    {
        return $this
            ->createQueryBuilder('post')
            ->where('post.category = 3')
            ->having('post.tags != 3')
            ->orderBy('post.id','DESC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function getFinNews()
    {
        return $this
            ->createQueryBuilder('post')
            ->where('post.category = 2')
            ->having('post.tags != 3')
            ->orderBy('post.id','DESC')
            ->getQuery()
            ->getResult()
            ;
    }
}
